[package]
name = "penrose_config"
version = "0.1.0"
authors = ["lewis-weinberger"]
edition = "2018"

[dependencies]
penrose = { git = "https://github.com/sminez/penrose", branch = "develop" }
simplelog = "0.8"
